#ifndef GENGINEMODELOBJECTTYPES_H
#define GENGINEMODELOBJECTTYPES_H
#include <gBase/gtypes.h>


namespace gfw
{
enum GENGINEMODEL_OBJECTTYPES
{
    GEM_OBJECT,
    GEM_PROPERTY,
    GEM_ENGINE,
    GEM_SCRIPTINSTANCE,
    GEM_SCRIPTINTEREFACE,
    GEM_TIMER

};
}
#endif // GENGINEMODELOBJECTTYPES_H
